// <auto-generated />
using Livraria.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Livraria.Migrations
{
    [DbContext(typeof(LivrariaContext))]
    partial class LivrariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Livraria.Domain.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Authors")
                        .HasColumnName("authors")
                        .HasMaxLength(300);

                    b.Property<DateTime>("BuyDate")
                        .HasColumnName("buy_date");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnName("buy_price");

                    b.Property<string>("Edition")
                        .HasColumnName("edition")
                        .HasMaxLength(100);

                    b.Property<string>("ISBN")
                        .HasColumnName("isbn")
                        .HasMaxLength(13);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(300);

                    b.Property<decimal>("Price")
                        .HasColumnName("price");

                    b.Property<int?>("PublishYear")
                        .HasColumnName("publish_year");

                    b.Property<DateTime?>("SellDate")
                        .HasColumnName("sell_date");

                    b.Property<decimal?>("SellPrice")
                        .HasColumnName("sell_price");

                    b.HasKey("ID");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
